name: claculator app workflow

on:
  push:
    branches:
     - main

   pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

  
  steps:
  - name: checkout code
    uses: actions/checkout@v2

  - name: Set up python 
    uses: actions/setup-python@v2
    with:
      python-version: "3.9"

  
  - name: Install dependencies
    run: |
     python -m pip install --upgrade pip
     pip insatll requirements.txt

  - name: run test
    run: |
    pytest _test.py 

